### ISSUE TITLE
Check the \"access token\" parameter

### ISSUE THREAD

**Issue by rockers007** [mosufy/lumen-api#1]
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter

**Comment by rockers007** [comment]
Be sure you have added Authorization: Bearer DfkN9pVwrgYFPJ5qlw7eVvLvdCwjPqcHihQCUzcV in header of request data.

DfkN9pVwrgYFPJ5qlw7eVvLvdCwjPqcHihQCUzcV  its token either for client or user.
will solve this issue

**Comment by mosufy** [comment]
Will update the DocBlocks and create Documentation before official release for better usage and understanding.
